# Generated by Django 3.2.2 on 2021-05-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_token_sent_at',
            field=models.DateTimeField(null=True, verbose_name='Email Token Sent at'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_verification_token',
            field=models.CharField(max_length=51, null=True, unique=True, verbose_name='Email Verification Token'),
        ),
    ]
