# Generated by Django 3.2.2 on 2021-05-11 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210511_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email_verification_token',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Email Verification Token'),
        ),
    ]
