# Generated by Django 3.2.2 on 2021-05-11 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_email_verification_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password_reset_sent_at',
            field=models.DateTimeField(null=True, verbose_name='Password Reset Sent at'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='password_reset_token',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Password Reset Token'),
        ),
    ]
